name: Web deployment
on:
  push:
    paths:
      - ".github/workflows/**"
      - "simple_matrix_client/**"
      - "**.nim"
      - "public/**"
      - "simple_matrix_client.nimble"

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: devel

      - name: Setup Dart Sass, Google Closure Compiler, html-minifer
        run: npm install -g sass google-closure-compiler html-minifier

      - name: Install dependencies
        run: nimble install -y

      - name: Build Sass
        run: nimble sass

      - name: Compile release build
        run: nimble buildjs

      - name: Minify JS
        run: google-closure-compiler public/js/simple_matrix_client.js --js_output_file public/js/simple_matrix_client.js

      - name: Minify HTML
        run: html-minifier --collapse-whitespace --remove-optional-tags --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype public/index.html -o public/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.